### ISSUE TITLE
rosbags collection methods

### ISSUE THREAD

**Issue by jasonjabbour** [robotperf/rosbags#1]
Hi! I'm currently working on generating a rosbag for benchmarking the stereo_image_proc package. This package would need recorded data from a left and right camera. Would it be reasonable to create a robot in gazebo with two cameras and record a rosbag in that manner? 

Could you specify how you collected the image2 rosbag? Is there complementary code to generate the data?

**Comment by vmayoral** [comment]
> Hi! I'm currently working on generating a rosbag for benchmarking the stereo_image_proc package. This package would need recorded data from a left and right camera. Would it be reasonable to create a robot in gazebo with two cameras and record a rosbag in that manner?

That'd be great. See https://github.com/ros-acceleration/acceleration_examples/blob/main/graphs/perception/perception_2nodes/worlds/camera_dynamic.world for the world created for the monocular camera use case ([launch file](https://github.com/ros-acceleration/acceleration_examples/blob/main/graphs/perception/perception_2nodes/launch/simulation.launch.py)). You should be able to extend this easily to create multiple cameras. See tutorials for stereo simulation.

> Could you specify how you collected the image2 rosbag? Is there complementary code to generate the data?

`ros2 bag record`
